tasks:
  - init: pip install -r requirements.txt' 
    command: python wsgi.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    visibility: public
